import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, stat, symlink, utimes } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { registerCoreTools } from "../src/bootstrap";
import type { BabConfig } from "../src/config";
import { BabServer } from "../src/server";
import {
  generateSkillContent,
  STATIC_TOOL_NAMES,
} from "../src/skills/generator";
import {
  computeFingerprint,
  discoverAgents,
  type GenerateResult,
  isStale,
  regenerateSkills,
} from "../src/skills/index";
import { VERSION } from "../src/version";

function makeTempConfig(baseDir: string): BabConfig {
  return {
    env: {},
    lazyTools: false,
    paths: {
      baseDir,
      envFile: join(baseDir, "env"),
      pluginsDir: join(baseDir, "plugins"),
      promptsDir: join(baseDir, "prompts"),
    },
    persistence: {
      enabled: false,
      enabledTools: new Set(),
      disabledTools: new Set(),
    },
  };
}

function makeStubResult(): GenerateResult {
  return {
    content: {
      skillMd: `---
name: bab
description: Test skill
user-invocable: false
---
<!-- Auto-generated by bab v${VERSION} -->
# Bab MCP Tools
`,
      toolsReference: "# Tools Reference\n",
      delegatePluginsReference: "# Delegate Plugins Reference\n",
    },
    toolNames: ["chat"],
    pluginIds: [],
  };
}

function captureStderr(): {
  stream: { write(chunk: string): boolean };
  output: string[];
} {
  const output: string[] = [];
  return {
    stream: {
      write(chunk: string) {
        output.push(chunk);
        return true;
      },
    },
    output,
  };
}

describe("computeFingerprint", () => {
  test("produces a 64-char hex string", () => {
    const fp = computeFingerprint("1.0.0", ["a"], ["chat"]);
    expect(fp).toMatch(/^[0-9a-f]{64}$/);
  });

  test("same inputs produce same fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["x", "y"], ["chat", "debug"]);
    const b = computeFingerprint("1.0.0", ["x", "y"], ["chat", "debug"]);
    expect(a).toBe(b);
  });

  test("order of plugins and tools does not matter", () => {
    const a = computeFingerprint("1.0.0", ["b", "a"], ["debug", "chat"]);
    const b = computeFingerprint("1.0.0", ["a", "b"], ["chat", "debug"]);
    expect(a).toBe(b);
  });

  test("different version produces different fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["a"], ["chat"]);
    const b = computeFingerprint("2.0.0", ["a"], ["chat"]);
    expect(a).not.toBe(b);
  });

  test("different plugins produce different fingerprint", () => {
    const a = computeFingerprint("1.0.0", ["a"], ["chat"]);
    const b = computeFingerprint("1.0.0", ["a", "b"], ["chat"]);
    expect(a).not.toBe(b);
  });
});

describe("isStale", () => {
  test("returns true when no existing metadata", () => {
    expect(isStale(undefined, "abc123")).toBeTrue();
  });

  test("returns true when fingerprints differ", () => {
    const existing = {
      schema_version: 1 as const,
      bab_version: VERSION,
      generated_at: new Date().toISOString(),
      fingerprint: "old-fingerprint",
    };
    expect(isStale(existing, "new-fingerprint")).toBeTrue();
  });

  test("returns false when fingerprints match", () => {
    const fp = "matching-fingerprint";
    const existing = {
      schema_version: 1 as const,
      bab_version: VERSION,
      generated_at: new Date().toISOString(),
      fingerprint: fp,
    };
    expect(isStale(existing, fp)).toBeFalse();
  });
});

describe("discoverAgents", () => {
  test("returns agents whose config directories exist", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const agents = await discoverAgents(undefined, home);

    expect(agents.length).toBe(1);
    expect(agents[0].id).toBe("claude");
  });

  test("returns empty when no agent directories exist", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-empty-"));
    const agents = await discoverAgents(undefined, home);
    expect(agents).toEqual([]);
  });

  test("filters by agent id", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-agents-filter-"));
    await mkdir(join(home, ".claude"), { recursive: true });
    await mkdir(join(home, ".codex"), { recursive: true });

    const claude = await discoverAgents("claude", home);
    expect(claude.length).toBe(1);
    expect(claude[0].id).toBe("claude");

    const codex = await discoverAgents("codex", home);
    expect(codex.length).toBe(1);
    expect(codex[0].id).toBe("codex");

    const unknown = await discoverAgents("unknown-agent", home);
    expect(unknown).toEqual([]);
  });
});

describe("regenerateSkills", () => {
  test("writes skill directory for discovered agents", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-regen-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const stderr = captureStderr();
    const stubResult = makeStubResult();

    const result = await regenerateSkills(async () => stubResult, {
      force: true,
      agent: "claude",
      home,
      stderr: stderr.stream,
    });

    expect(result.agentsUpdated).toContain("claude");

    const skillMdPath = join(home, ".claude", "skills", "bab", "SKILL.md");
    const metadataPath = join(
      home,
      ".claude",
      "skills",
      "bab",
      ".bab-skills.json",
    );
    const toolsRefPath = join(
      home,
      ".claude",
      "skills",
      "bab",
      "references",
      "tools.md",
    );

    expect((await stat(skillMdPath)).isFile()).toBeTrue();
    expect((await stat(metadataPath)).isFile()).toBeTrue();
    expect((await stat(toolsRefPath)).isFile()).toBeTrue();

    const metadata = JSON.parse(await Bun.file(metadataPath).text());
    expect(metadata.schema_version).toBe(1);
    expect(metadata.bab_version).toBe(VERSION);
    expect(metadata.fingerprint).toMatch(/^[0-9a-f]{64}$/);
  });

  test("skips agents when fingerprint is fresh (not forced)", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-skip-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const stderr = captureStderr();
    const stubResult = makeStubResult();

    const firstResult = await regenerateSkills(async () => stubResult, {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(firstResult.agentsUpdated).toContain("claude");

    const secondResult = await regenerateSkills(async () => stubResult, {
      force: false,
      home,
      stderr: stderr.stream,
    });

    expect(secondResult.skipped).toContain("claude");
    expect(secondResult.agentsUpdated).not.toContain("claude");
  });

  test("returns empty when no agents detected", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-noagent-"));
    const stderr = captureStderr();

    const result = await regenerateSkills(async () => makeStubResult(), {
      agent: "nonexistent-agent",
      home,
      stderr: stderr.stream,
    });

    expect(result.agentsUpdated).toEqual([]);
    expect(result.skipped).toEqual([]);
  });

  test("skips user-modified SKILL.md", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-usermod-"));
    const skillBabDir = join(home, ".claude", "skills", "bab");
    await mkdir(skillBabDir, { recursive: true });

    await Bun.write(
      join(skillBabDir, "SKILL.md"),
      "---\nname: bab\n---\n# My custom skill notes\n",
    );

    const stderr = captureStderr();

    const result = await regenerateSkills(async () => makeStubResult(), {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(result.skipped).toContain("claude");
    expect(stderr.output.join("")).toContain("user-modified");
  });

  test("skips when lock is held", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-lock-"));
    const skillsDir = join(home, ".claude", "skills");
    await mkdir(join(skillsDir, ".bab-skillgen.lock"), { recursive: true });

    const stderr = captureStderr();

    const result = await regenerateSkills(async () => makeStubResult(), {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(result.skipped).toContain("claude");
    expect(stderr.output.join("")).toContain("already in progress");
  });

  test("recovers stale lock older than 5 minutes", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-stalelock-"));
    const skillsDir = join(home, ".claude", "skills");
    const lockDir = join(skillsDir, ".bab-skillgen.lock");
    await mkdir(lockDir, { recursive: true });

    const staleTime = new Date(Date.now() - 10 * 60 * 1000);
    await utimes(lockDir, staleTime, staleTime);

    const stderr = captureStderr();

    const result = await regenerateSkills(async () => makeStubResult(), {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(result.agentsUpdated).toContain("claude");
    expect(result.skipped).not.toContain("claude");
  });

  test("skips symlinked skills directory", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-symlink-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const target = await mkdtemp(join(tmpdir(), "bab-symtarget-"));
    await symlink(target, join(home, ".claude", "skills"));

    const stderr = captureStderr();

    const result = await regenerateSkills(async () => makeStubResult(), {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(result.skipped).toContain("claude");
    expect(stderr.output.join("")).toContain("symlink");
  });

  test("cleans up orphan staging directories", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-orphan-"));
    const skillsDir = join(home, ".claude", "skills");
    const orphanStaging = join(skillsDir, ".bab-staging-old-nonce");
    const orphanOld = join(skillsDir, ".bab-old-old-nonce");
    await mkdir(orphanStaging, { recursive: true });
    await mkdir(orphanOld, { recursive: true });

    const stderr = captureStderr();

    await regenerateSkills(async () => makeStubResult(), {
      force: true,
      home,
      stderr: stderr.stream,
    });

    let stagingExists = true;
    let oldExists = true;
    try {
      await stat(orphanStaging);
    } catch {
      stagingExists = false;
    }
    try {
      await stat(orphanOld);
    } catch {
      oldExists = false;
    }

    expect(stagingExists).toBeFalse();
    expect(oldExists).toBeFalse();
  });
});

describe("STATIC_TOOL_NAMES", () => {
  test("contains expected core tools", () => {
    expect(STATIC_TOOL_NAMES).toContain("chat");
    expect(STATIC_TOOL_NAMES).toContain("thinkdeep");
    expect(STATIC_TOOL_NAMES).toContain("codereview");
    expect(STATIC_TOOL_NAMES).toContain("delegate");
    expect(STATIC_TOOL_NAMES).toContain("version");
  });

  test("has no duplicates", () => {
    const unique = new Set(STATIC_TOOL_NAMES);
    expect(unique.size).toBe(STATIC_TOOL_NAMES.length);
  });
});

describe("generateSkillContent", () => {
  test("generates SKILL.md with frontmatter and auto-generated marker", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const result = await generateSkillContent(config);

    expect(result.content.skillMd).toContain("---\nname: bab");
    expect(result.content.skillMd).toContain("user-invocable: false");
    expect(result.content.skillMd).toContain(
      `Auto-generated by bab v${VERSION}`,
    );
    expect(result.content.skillMd).toContain(
      "| Tool | Description | When to use |",
    );
    expect(result.toolNames).toEqual(STATIC_TOOL_NAMES);
    expect(Array.isArray(result.pluginIds)).toBeTrue();
  });

  test("generates tools reference with all catalog entries", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-tools-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const result = await generateSkillContent(config);

    for (const toolName of STATIC_TOOL_NAMES) {
      expect(result.content.toolsReference).toContain(`## \`${toolName}\``);
    }
  });

  test("generates delegate plugins reference", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-gen-plugins-"));
    const config = makeTempConfig(home);
    await mkdir(config.paths.pluginsDir, { recursive: true });

    const result = await generateSkillContent(config);

    expect(result.content.delegatePluginsReference).toContain(
      "Delegate Plugins Reference",
    );
  });
});

describe("post-add/remove skill regeneration", () => {
  test("regenerateSkills updates agents after plugin change", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-postadd-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const stderr = captureStderr();
    const stubResult = makeStubResult();

    const result = await regenerateSkills(async () => stubResult, {
      force: true,
      home,
      stderr: stderr.stream,
    });

    expect(result.agentsUpdated).toContain("claude");

    const skillMdPath = join(home, ".claude", "skills", "bab", "SKILL.md");
    expect((await stat(skillMdPath)).isFile()).toBeTrue();
  });

  test("regenerateSkills with changed plugins produces new fingerprint", async () => {
    const home = await mkdtemp(join(tmpdir(), "bab-pluginchange-"));
    await mkdir(join(home, ".claude"), { recursive: true });

    const stderr = captureStderr();

    const resultA = makeStubResult();
    resultA.pluginIds = ["plugin-a"];
    await regenerateSkills(async () => resultA, {
      force: true,
      home,
      stderr: stderr.stream,
    });

    const metadataPathA = join(
      home,
      ".claude",
      "skills",
      "bab",
      ".bab-skills.json",
    );
    const metaA = JSON.parse(await Bun.file(metadataPathA).text());

    const resultB = makeStubResult();
    resultB.pluginIds = ["plugin-a", "plugin-b"];
    await regenerateSkills(async () => resultB, {
      force: true,
      home,
      stderr: stderr.stream,
    });

    const metaB = JSON.parse(await Bun.file(metadataPathA).text());
    expect(metaA.fingerprint).not.toBe(metaB.fingerprint);
  });
});

describe("startup tool registration", () => {
  test("registered tool names match STATIC_TOOL_NAMES catalog", async () => {
    const config = makeTempConfig("/tmp/bab-startup-test");
    const server = new BabServer();
    registerCoreTools(server, config);

    const registeredNames = Array.from(server.toolRegistry.keys()).sort();
    const catalogNames = [...STATIC_TOOL_NAMES].sort();

    expect(registeredNames).toEqual(catalogNames);
  });
});
