import { createHash } from "node:crypto";
import { constants as FS } from "node:fs";
import {
  access,
  lstat,
  mkdir,
  readdir,
  realpath,
  rename,
  rm,
  stat,
} from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

import { z } from "zod/v4";
import type { WritableLike } from "../commands/shared";

import { VERSION } from "../version";

export interface AgentTarget {
  id: string;
  configDir: string;
  skillsDir: string;
}

export interface RegenerateSkillsOptions {
  force?: boolean;
  agent?: string;
  home?: string;
  stderr?: WritableLike;
}

export interface SkillContent {
  skillMd: string;
  toolsReference: string;
  delegatePluginsReference: string;
}

const SkillsMetadataSchema = z.object({
  schema_version: z.literal(1),
  bab_version: z.string(),
  generated_at: z.string(),
  fingerprint: z.string(),
});

type SkillsMetadata = z.infer<typeof SkillsMetadataSchema>;

const AUTO_GENERATED_MARKER = "<!-- Auto-generated by bab v";
const STALE_DIR_PREFIX_STAGING = ".bab-staging-";
const STALE_DIR_PREFIX_OLD = ".bab-old-";
const LOCK_DIR_NAME = ".bab-skillgen.lock";
const STALE_LOCK_MS = 5 * 60 * 1000;

function getKnownAgents(home = homedir()): AgentTarget[] {
  return [
    {
      id: "claude",
      configDir: join(home, ".claude"),
      skillsDir: join(home, ".claude", "skills"),
    },
    {
      id: "codex",
      configDir: join(home, ".codex"),
      skillsDir: join(home, ".codex", "skills"),
    },
  ];
}

async function directoryExists(path: string): Promise<boolean> {
  try {
    const stats = await stat(path);
    return stats.isDirectory();
  } catch {
    return false;
  }
}

async function isSymlink(path: string): Promise<boolean> {
  try {
    const stats = await lstat(path);
    return stats.isSymbolicLink();
  } catch {
    return false;
  }
}

export async function discoverAgents(
  agentFilter?: string,
  home?: string,
): Promise<AgentTarget[]> {
  const known = getKnownAgents(home);
  const candidates = agentFilter
    ? known.filter((a) => a.id === agentFilter)
    : known;

  const detected: AgentTarget[] = [];

  for (const agent of candidates) {
    if (await directoryExists(agent.configDir)) {
      detected.push(agent);
    }
  }

  return detected;
}

export function computeFingerprint(
  babVersion: string,
  pluginIds: string[],
  toolNames: string[],
): string {
  const sorted_plugins = [...pluginIds].sort();
  const sorted_tools = [...toolNames].sort();
  const input = `${babVersion}:${sorted_plugins.join(",")}:${sorted_tools.join(",")}`;
  return createHash("sha256").update(input).digest("hex");
}

async function readMetadata(
  skillDir: string,
  stderr: WritableLike,
): Promise<SkillsMetadata | undefined> {
  const metadataPath = join(skillDir, "bab", ".bab-skills.json");

  try {
    await access(metadataPath, FS.F_OK);
  } catch {
    return undefined;
  }

  try {
    const contents = await Bun.file(metadataPath).text();
    return SkillsMetadataSchema.parse(JSON.parse(contents));
  } catch (error) {
    stderr.write(
      `Warning: failed to read ${metadataPath}: ${error instanceof Error ? error.message : String(error)}\n`,
    );
    return undefined;
  }
}

export function isStale(
  existing: SkillsMetadata | undefined,
  currentFingerprint: string,
): boolean {
  if (!existing) {
    return true;
  }

  return existing.fingerprint !== currentFingerprint;
}

async function isUserModified(
  skillDir: string,
  stderr: WritableLike,
): Promise<boolean> {
  const skillMdPath = join(skillDir, "bab", "SKILL.md");

  try {
    await access(skillMdPath, FS.F_OK);
  } catch {
    return false;
  }

  try {
    const contents = await Bun.file(skillMdPath).text();

    if (!contents.includes(AUTO_GENERATED_MARKER)) {
      stderr.write(
        `Warning: ${skillMdPath} appears user-modified (missing auto-generated header), skipping\n`,
      );
      return true;
    }

    return false;
  } catch (error) {
    stderr.write(
      `Warning: cannot read ${skillMdPath} (${error instanceof Error ? error.message : String(error)}); skipping\n`,
    );
    return true;
  }
}

async function acquireLock(skillsDir: string): Promise<boolean> {
  const lockDir = join(skillsDir, LOCK_DIR_NAME);

  try {
    await mkdir(lockDir);
    return true;
  } catch {
    try {
      const lockStats = await stat(lockDir);
      const ageMs = Date.now() - lockStats.mtimeMs;

      if (ageMs > STALE_LOCK_MS) {
        await rm(lockDir, { force: true, recursive: true });
        await mkdir(lockDir);
        return true;
      }
    } catch {
      // lock dir vanished between checks — retry once
      try {
        await mkdir(lockDir);
        return true;
      } catch {
        return false;
      }
    }

    return false;
  }
}

async function releaseLock(skillsDir: string): Promise<void> {
  await rm(join(skillsDir, LOCK_DIR_NAME), {
    force: true,
    recursive: true,
  }).catch(() => {});
}

async function cleanupOrphanDirs(skillsDir: string): Promise<void> {
  try {
    const entries = await readdir(skillsDir);

    for (const entry of entries) {
      if (
        entry.startsWith(STALE_DIR_PREFIX_STAGING) ||
        entry.startsWith(STALE_DIR_PREFIX_OLD)
      ) {
        await rm(join(skillsDir, entry), {
          force: true,
          recursive: true,
        }).catch(() => {});
      }
    }
  } catch {
    // skills dir may not exist yet
  }
}

async function writeSkillDirectory(
  skillsDir: string,
  content: SkillContent,
  metadata: SkillsMetadata,
  stderr: WritableLike,
): Promise<boolean> {
  const nonce = crypto.randomUUID();
  const stagingDir = join(skillsDir, `.bab-staging-${nonce}`);
  const finalDir = join(skillsDir, "bab");
  const oldDir = join(skillsDir, `.bab-old-${nonce}`);
  let movedOld = false;

  try {
    await mkdir(stagingDir, { recursive: true });
    await mkdir(join(stagingDir, "references"), { recursive: true });

    await Bun.write(join(stagingDir, "SKILL.md"), content.skillMd);
    await Bun.write(
      join(stagingDir, "references", "tools.md"),
      content.toolsReference,
    );
    await Bun.write(
      join(stagingDir, "references", "delegate-plugins.md"),
      content.delegatePluginsReference,
    );
    await Bun.write(
      join(stagingDir, ".bab-skills.json"),
      `${JSON.stringify(metadata, null, 2)}\n`,
    );

    if (await directoryExists(finalDir)) {
      await rename(finalDir, oldDir);
      movedOld = true;
    }

    await rename(stagingDir, finalDir);

    if (movedOld) {
      await rm(oldDir, { force: true, recursive: true });
    }

    return true;
  } catch (error) {
    if (movedOld && (await directoryExists(oldDir))) {
      try {
        if (await directoryExists(finalDir)) {
          await rm(finalDir, { force: true, recursive: true });
        }
        await rename(oldDir, finalDir);
      } catch {
        stderr.write(
          `Warning: failed to restore previous bab skill directory at ${finalDir}\n`,
        );
      }
    }

    await rm(stagingDir, { force: true, recursive: true }).catch(() => {});

    throw error;
  }
}

export interface GenerateResult {
  content: SkillContent;
  toolNames: string[];
  pluginIds: string[];
}

export async function regenerateSkills(
  generateContent: () => Promise<GenerateResult>,
  options: RegenerateSkillsOptions = {},
): Promise<{ agentsUpdated: string[]; skipped: string[] }> {
  const stderr = options.stderr ?? process.stderr;

  const agents = await discoverAgents(options.agent, options.home);

  if (agents.length === 0) {
    return { agentsUpdated: [], skipped: [] };
  }

  const agentsUpdated: string[] = [];
  const skipped: string[] = [];

  let generated: GenerateResult | undefined;
  let fingerprint: string | undefined;

  async function ensureGenerated(): Promise<void> {
    if (!generated) {
      generated = await generateContent();
      fingerprint = computeFingerprint(
        VERSION,
        generated.pluginIds,
        generated.toolNames,
      );
    }
  }

  for (const agent of agents) {
    try {
      if (await isSymlink(agent.skillsDir)) {
        stderr.write(
          `Warning: ${agent.skillsDir} is a symlink, skipping for safety\n`,
        );
        skipped.push(agent.id);
        continue;
      }

      if (!(await directoryExists(agent.skillsDir))) {
        await mkdir(agent.skillsDir, { recursive: true });
      }

      let resolvedSkillsDir: string;
      try {
        resolvedSkillsDir = await realpath(agent.skillsDir);
      } catch {
        stderr.write(
          `Warning: cannot resolve ${agent.skillsDir}, skipping\n`,
        );
        skipped.push(agent.id);
        continue;
      }

      let resolvedConfigDir: string;
      try {
        resolvedConfigDir = await realpath(agent.configDir);
      } catch {
        stderr.write(
          `Warning: cannot resolve config dir ${agent.configDir}, skipping\n`,
        );
        skipped.push(agent.id);
        continue;
      }

      if (!resolvedSkillsDir.startsWith(resolvedConfigDir + "/")) {
        stderr.write(
          `Warning: ${agent.skillsDir} resolves outside config dir, skipping\n`,
        );
        skipped.push(agent.id);
        continue;
      }

      await cleanupOrphanDirs(resolvedSkillsDir);

      if (!options.force) {
        const existing = await readMetadata(resolvedSkillsDir, stderr);

        if (existing) {
          await ensureGenerated();

          if (!isStale(existing, fingerprint as string)) {
            skipped.push(agent.id);
            continue;
          }
        }
      }

      if (await isUserModified(resolvedSkillsDir, stderr)) {
        skipped.push(agent.id);
        continue;
      }

      await ensureGenerated();

      const metadata: SkillsMetadata = {
        schema_version: 1,
        bab_version: VERSION,
        generated_at: new Date().toISOString(),
        fingerprint: fingerprint as string,
      };

      const locked = await acquireLock(resolvedSkillsDir);

      if (!locked) {
        stderr.write(
          `Warning: skill generation already in progress for ${agent.id}, skipping\n`,
        );
        skipped.push(agent.id);
        continue;
      }

      try {
        const written = await writeSkillDirectory(
          resolvedSkillsDir,
          (generated as GenerateResult).content,
          metadata,
          stderr,
        );

        if (written) {
          agentsUpdated.push(agent.id);
        }
      } finally {
        await releaseLock(resolvedSkillsDir);
      }
    } catch (error) {
      stderr.write(
        `Warning: failed to write skills for ${agent.id}: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      skipped.push(agent.id);
    }
  }

  return { agentsUpdated, skipped };
}
