import type { Dirent } from "node:fs";
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

export interface BundledExtraFile {
  content: string;
  path: string;
}

export interface BundledPlugin {
  adapterSource: string | undefined;
  extraFiles: BundledExtraFile[];
  id: string;
  manifestYaml: string;
}

const RESERVED_FILES = new Set(["manifest.yaml", "adapter.ts"]);

export async function readBundledPluginsFromDisk(
  pluginsRoot: string,
): Promise<BundledPlugin[]> {
  let entries: Dirent[];
  try {
    entries = await readdir(pluginsRoot, { withFileTypes: true });
  } catch {
    return [];
  }

  const plugins: BundledPlugin[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    const pluginDirectory = join(pluginsRoot, entry.name);
    const manifestPath = join(pluginDirectory, "manifest.yaml");

    let manifestYaml: string;
    try {
      manifestYaml = await readFile(manifestPath, "utf8");
    } catch {
      continue;
    }

    const id = entry.name;
    const adapterPath = join(pluginDirectory, "adapter.ts");
    const adapterSource = await readFile(adapterPath, "utf8")
      .then((content) => content)
      .catch(() => undefined);

    const extraFiles = await collectExtraFiles(pluginDirectory, id);

    plugins.push({
      adapterSource,
      extraFiles,
      id,
      manifestYaml,
    });
  }

  return plugins.sort((left, right) => left.id.localeCompare(right.id));
}

async function collectExtraFiles(
  pluginDirectory: string,
  _pluginId: string,
): Promise<BundledExtraFile[]> {
  const allFiles: BundledExtraFile[] = [];

  async function walk(current: string): Promise<void> {
    const entries = await readdir(current, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
        continue;
      }
      if (!entry.isFile()) {
        continue;
      }
      const rel = relative(pluginDirectory, full);
      if (RESERVED_FILES.has(rel)) {
        continue;
      }
      const content = await readFile(full, "utf8");
      allFiles.push({ content, path: rel });
    }
  }

  try {
    await walk(pluginDirectory);
  } catch {
    return [];
  }

  return allFiles.sort((left, right) => left.path.localeCompare(right.path));
}

function escapeForTemplate(literal: string): string {
  return literal
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");
}

export function renderBundledPluginsModule(plugins: BundledPlugin[]): string {
  const header = [
    "// This file is generated by scripts/bundle-plugins.ts.",
    "// Do not edit by hand. Re-run `bun run prebuild:binary` after editing files under plugins/.",
    "",
    'import type { BundledPlugin } from "../scripts/bundle-plugins";',
    "",
    `export const bundledPlugins: BundledPlugin[] = [`,
  ].join("\n");

  const records = plugins
    .map((plugin) => {
      const adapterLiteral = plugin.adapterSource
        ? `      adapterSource: \`${escapeForTemplate(plugin.adapterSource)}\`,`
        : `      adapterSource: undefined,`;
      const manifestLiteral = `      manifestYaml: \`${escapeForTemplate(plugin.manifestYaml)}\`,`;
      const idLiteral = `      id: ${JSON.stringify(plugin.id)},`;
      const extraFilesLiteral = `      extraFiles: ${
        plugin.extraFiles.length === 0
          ? "[]"
          : `[\n${plugin.extraFiles
              .map(
                (file) =>
                  `        { path: ${JSON.stringify(file.path)}, content: \`${escapeForTemplate(file.content)}\` },`,
              )
              .join("\n")}\n      ]`
      },`;
      return `    {\n${idLiteral}\n${manifestLiteral}\n${adapterLiteral}\n${extraFilesLiteral}\n    },`;
    })
    .join("\n");

  return `${header}\n${records}\n  ];\n`;
}

export async function extractBundledPlugins(
  targetRoot: string,
  plugins: BundledPlugin[],
): Promise<string> {
  await mkdir(targetRoot, { recursive: true });

  for (const plugin of plugins) {
    const pluginDirectory = join(targetRoot, plugin.id);
    await mkdir(pluginDirectory, { recursive: true });
    await writeIfChanged(
      join(pluginDirectory, "manifest.yaml"),
      plugin.manifestYaml,
    );

    if (plugin.adapterSource !== undefined) {
      await writeIfChanged(
        join(pluginDirectory, "adapter.ts"),
        plugin.adapterSource,
      );
    }

    for (const file of plugin.extraFiles) {
      const full = join(pluginDirectory, ...file.path.split("/"));
      const parent = dirname(full);
      if (parent && parent !== full) {
        await mkdir(parent, { recursive: true });
      }
      await writeIfChanged(full, file.content);
    }
  }

  return targetRoot;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  let existing: string | undefined;
  try {
    existing = await readFile(path, "utf8");
  } catch {
    // not present
  }

  if (existing === content) {
    return;
  }

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

async function main(): Promise<void> {
  const pluginsRoot = process.argv[2] ?? join(process.cwd(), "plugins");
  const outputPath =
    process.argv[3] ?? join(process.cwd(), "src", "bundled-plugins.gen.ts");

  const plugins = await readBundledPluginsFromDisk(pluginsRoot);

  try {
    await stat(pluginsRoot);
  } catch {
    console.error(`No bundled plugins directory at ${pluginsRoot}`);
    process.exit(0);
  }

  const code = renderBundledPluginsModule(plugins);
  await writeFile(outputPath, code);
  console.log(
    `Wrote ${plugins.length} bundled plugin(s) to ${outputPath}`.replaceAll(
      sep,
      "/",
    ),
  );
}

if (import.meta.main) {
  await main();
}
